/**
 * Base de datos de 118 elementos químicos
 * Tabla Periódica Interactiva - meskeIA
 */

export interface Elemento {
  numero: number;
  simbolo: string;
  nombre: string;
  masa: number;
  grupo: number;
  periodo: number;
  familia: string;
  estado: string;
  electronegatividad: number | null;
  radioAtomico: number | null;
  configuracionElectronica: string;
  usos: string[];
  datoCurioso: string;
}

export type FamiliaElemento =
  | 'metales-alcalinos'
  | 'metales-alcalinoterreos'
  | 'metales-transicion'
  | 'metaloides'
  | 'no-metales'
  | 'halogenos'
  | 'gases-nobles'
  | 'lantanidos'
  | 'actinidos'
  | 'otros-metales';

export const FAMILIAS: Record<string, { nombre: string; color: string }> = {
  'metales-alcalinos': { nombre: 'Metales Alcalinos', color: '#FF6B6B' },
  'metales-alcalinoterreos': { nombre: 'Metales Alcalinotérreos', color: '#FFB347' },
  'metales-transicion': { nombre: 'Metales de Transición', color: '#87CEEB' },
  'metaloides': { nombre: 'Metaloides', color: '#98D8C8' },
  'no-metales': { nombre: 'No Metales', color: '#C3B1E1' },
  'halogenos': { nombre: 'Halógenos', color: '#F9E79F' },
  'gases-nobles': { nombre: 'Gases Nobles', color: '#AED6F1' },
  'lantanidos': { nombre: 'Lantánidos', color: '#F5B7B1' },
  'actinidos': { nombre: 'Actínidos', color: '#D5DBDB' },
  'otros-metales': { nombre: 'Otros Metales', color: '#A9DFBF' },
};

export const ESTADOS: Record<string, string> = {
  'solido': 'Sólido',
  'liquido': 'Líquido',
  'gas': 'Gas',
  'sintetico': 'Sintético',
};

export const elementos: Elemento[] = [
  // Período 1
  { numero: 1, simbolo: "H", nombre: "Hidrógeno", masa: 1.008, grupo: 1, periodo: 1, familia: "no-metales", estado: "gas", electronegatividad: 2.20, radioAtomico: 53, configuracionElectronica: "1s¹", usos: ["Combustible en cohetes", "Soldadura", "Refinado de petróleo"], datoCurioso: "Es el elemento más abundante del universo, constituyendo el 75% de la materia visible." },
  { numero: 2, simbolo: "He", nombre: "Helio", masa: 4.003, grupo: 18, periodo: 1, familia: "gases-nobles", estado: "gas", electronegatividad: null, radioAtomico: 31, configuracionElectronica: "1s²", usos: ["Globos", "Criogenia", "Respiración profunda"], datoCurioso: "Es el segundo elemento más abundante del universo, pero raro en la Tierra." },

  // Período 2
  { numero: 3, simbolo: "Li", nombre: "Litio", masa: 6.941, grupo: 1, periodo: 2, familia: "metales-alcalinos", estado: "solido", electronegatividad: 0.98, radioAtomico: 167, configuracionElectronica: "[He] 2s¹", usos: ["Baterías", "Medicamentos", "Aleaciones"], datoCurioso: "Es el metal más ligero y puede flotar en el agua." },
  { numero: 4, simbolo: "Be", nombre: "Berilio", masa: 9.012, grupo: 2, periodo: 2, familia: "metales-alcalinoterreos", estado: "solido", electronegatividad: 1.57, radioAtomico: 112, configuracionElectronica: "[He] 2s²", usos: ["Aleaciones aeroespaciales", "Rayos X", "Reactores nucleares"], datoCurioso: "Es extremadamente tóxico pero indispensable en aeronáutica." },
  { numero: 5, simbolo: "B", nombre: "Boro", masa: 10.811, grupo: 13, periodo: 2, familia: "metaloides", estado: "solido", electronegatividad: 2.04, radioAtomico: 87, configuracionElectronica: "[He] 2s² 2p¹", usos: ["Vidrio borosilicato", "Detergentes", "Semiconductores"], datoCurioso: "Forma enlaces químicos únicos que desafían las reglas tradicionales." },
  { numero: 6, simbolo: "C", nombre: "Carbono", masa: 12.011, grupo: 14, periodo: 2, familia: "no-metales", estado: "solido", electronegatividad: 2.55, radioAtomico: 67, configuracionElectronica: "[He] 2s² 2p²", usos: ["Base de vida orgánica", "Acero", "Diamantes", "Grafito"], datoCurioso: "Puede formar más compuestos que cualquier otro elemento." },
  { numero: 7, simbolo: "N", nombre: "Nitrógeno", masa: 14.007, grupo: 15, periodo: 2, familia: "no-metales", estado: "gas", electronegatividad: 3.04, radioAtomico: 56, configuracionElectronica: "[He] 2s² 2p³", usos: ["Fertilizantes", "Explosivos", "Criogenia"], datoCurioso: "Constituye el 78% de la atmósfera terrestre." },
  { numero: 8, simbolo: "O", nombre: "Oxígeno", masa: 15.999, grupo: 16, periodo: 2, familia: "no-metales", estado: "gas", electronegatividad: 3.44, radioAtomico: 48, configuracionElectronica: "[He] 2s² 2p⁴", usos: ["Respiración", "Combustión", "Medicina"], datoCurioso: "Es el elemento más abundante en la corteza terrestre." },
  { numero: 9, simbolo: "F", nombre: "Flúor", masa: 18.998, grupo: 17, periodo: 2, familia: "halogenos", estado: "gas", electronegatividad: 3.98, radioAtomico: 42, configuracionElectronica: "[He] 2s² 2p⁵", usos: ["Pasta dental", "Teflón", "Refrigerantes"], datoCurioso: "Es el elemento más electronegativo y reactivo." },
  { numero: 10, simbolo: "Ne", nombre: "Neón", masa: 20.180, grupo: 18, periodo: 2, familia: "gases-nobles", estado: "gas", electronegatividad: null, radioAtomico: 38, configuracionElectronica: "[He] 2s² 2p⁶", usos: ["Letreros luminosos", "Láseres", "Criogenia"], datoCurioso: "Produce luz naranja-rojiza cuando se electrifica." },

  // Período 3
  { numero: 11, simbolo: "Na", nombre: "Sodio", masa: 22.990, grupo: 1, periodo: 3, familia: "metales-alcalinos", estado: "solido", electronegatividad: 0.93, radioAtomico: 190, configuracionElectronica: "[Ne] 3s¹", usos: ["Sal de mesa", "Lámparas de vapor", "Aleaciones"], datoCurioso: "Se almacena en aceite por su alta reactividad." },
  { numero: 12, simbolo: "Mg", nombre: "Magnesio", masa: 24.305, grupo: 2, periodo: 3, familia: "metales-alcalinoterreos", estado: "solido", electronegatividad: 1.31, radioAtomico: 145, configuracionElectronica: "[Ne] 3s²", usos: ["Aleaciones ligeras", "Fuegos artificiales", "Antiácidos"], datoCurioso: "Arde con llama blanca brillante y es esencial para la clorofila." },
  { numero: 13, simbolo: "Al", nombre: "Aluminio", masa: 26.982, grupo: 13, periodo: 3, familia: "otros-metales", estado: "solido", electronegatividad: 1.61, radioAtomico: 118, configuracionElectronica: "[Ne] 3s² 3p¹", usos: ["Envases", "Construcción", "Transporte"], datoCurioso: "Una vez fue más valioso que el oro." },
  { numero: 14, simbolo: "Si", nombre: "Silicio", masa: 28.086, grupo: 14, periodo: 3, familia: "metaloides", estado: "solido", electronegatividad: 1.90, radioAtomico: 111, configuracionElectronica: "[Ne] 3s² 3p²", usos: ["Semiconductores", "Vidrio", "Cemento"], datoCurioso: "Base de la revolución digital, segundo más abundante en corteza." },
  { numero: 15, simbolo: "P", nombre: "Fósforo", masa: 30.974, grupo: 15, periodo: 3, familia: "no-metales", estado: "solido", electronegatividad: 2.19, radioAtomico: 98, configuracionElectronica: "[Ne] 3s² 3p³", usos: ["Fertilizantes", "Cerillas", "ADN/ARN"], datoCurioso: "El fósforo blanco brilla en la oscuridad." },
  { numero: 16, simbolo: "S", nombre: "Azufre", masa: 32.065, grupo: 16, periodo: 3, familia: "no-metales", estado: "solido", electronegatividad: 2.58, radioAtomico: 88, configuracionElectronica: "[Ne] 3s² 3p⁴", usos: ["Ácido sulfúrico", "Caucho", "Fertilizantes"], datoCurioso: "Conocido desde la antigüedad, asociado con el fuego." },
  { numero: 17, simbolo: "Cl", nombre: "Cloro", masa: 35.453, grupo: 17, periodo: 3, familia: "halogenos", estado: "gas", electronegatividad: 3.16, radioAtomico: 79, configuracionElectronica: "[Ne] 3s² 3p⁵", usos: ["Desinfectante", "PVC", "Tratamiento de agua"], datoCurioso: "Fue usado como arma química en la Primera Guerra Mundial." },
  { numero: 18, simbolo: "Ar", nombre: "Argón", masa: 39.948, grupo: 18, periodo: 3, familia: "gases-nobles", estado: "gas", electronegatividad: null, radioAtomico: 71, configuracionElectronica: "[Ne] 3s² 3p⁶", usos: ["Soldadura", "Lámparas", "Preservación"], datoCurioso: "Tercer gas más abundante en la atmósfera (~1%)." },

  // Período 4
  { numero: 19, simbolo: "K", nombre: "Potasio", masa: 39.098, grupo: 1, periodo: 4, familia: "metales-alcalinos", estado: "solido", electronegatividad: 0.82, radioAtomico: 243, configuracionElectronica: "[Ar] 4s¹", usos: ["Fertilizantes", "Medicina", "Fuegos artificiales"], datoCurioso: "Esencial para la función nerviosa y muscular." },
  { numero: 20, simbolo: "Ca", nombre: "Calcio", masa: 40.078, grupo: 2, periodo: 4, familia: "metales-alcalinoterreos", estado: "solido", electronegatividad: 1.00, radioAtomico: 194, configuracionElectronica: "[Ar] 4s²", usos: ["Huesos y dientes", "Cemento", "Metalurgia"], datoCurioso: "Quinto elemento más abundante en corteza terrestre." },
  { numero: 21, simbolo: "Sc", nombre: "Escandio", masa: 44.956, grupo: 3, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.36, radioAtomico: 184, configuracionElectronica: "[Ar] 3d¹ 4s²", usos: ["Aleaciones aeroespaciales", "Lámparas"], datoCurioso: "Predicho por Mendeleev como 'eka-boro'." },
  { numero: 22, simbolo: "Ti", nombre: "Titanio", masa: 47.867, grupo: 4, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.54, radioAtomico: 176, configuracionElectronica: "[Ar] 3d² 4s²", usos: ["Aeronáutica", "Implantes médicos", "Pigmentos"], datoCurioso: "Mayor resistencia a la corrosión, biocompatible." },
  { numero: 23, simbolo: "V", nombre: "Vanadio", masa: 50.942, grupo: 5, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.63, radioAtomico: 171, configuracionElectronica: "[Ar] 3d³ 4s²", usos: ["Acero de alta resistencia", "Catalizadores"], datoCurioso: "Forma compuestos de muchos colores diferentes." },
  { numero: 24, simbolo: "Cr", nombre: "Cromo", masa: 51.996, grupo: 6, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.66, radioAtomico: 166, configuracionElectronica: "[Ar] 3d⁵ 4s¹", usos: ["Cromado", "Acero inoxidable", "Pigmentos"], datoCurioso: "Da color a rubíes y esmeraldas." },
  { numero: 25, simbolo: "Mn", nombre: "Manganeso", masa: 54.938, grupo: 7, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.55, radioAtomico: 161, configuracionElectronica: "[Ar] 3d⁵ 4s²", usos: ["Acero", "Baterías", "Vidrio"], datoCurioso: "Esencial para la fotosíntesis en plantas." },
  { numero: 26, simbolo: "Fe", nombre: "Hierro", masa: 55.845, grupo: 8, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.83, radioAtomico: 156, configuracionElectronica: "[Ar] 3d⁶ 4s²", usos: ["Acero", "Construcción", "Maquinaria"], datoCurioso: "El núcleo de la Tierra es principalmente hierro." },
  { numero: 27, simbolo: "Co", nombre: "Cobalto", masa: 58.933, grupo: 9, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.88, radioAtomico: 152, configuracionElectronica: "[Ar] 3d⁷ 4s²", usos: ["Baterías", "Aleaciones", "Pigmentos azules"], datoCurioso: "Da color azul al vidrio desde la antigüedad." },
  { numero: 28, simbolo: "Ni", nombre: "Níquel", masa: 58.693, grupo: 10, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.91, radioAtomico: 149, configuracionElectronica: "[Ar] 3d⁸ 4s²", usos: ["Monedas", "Acero inoxidable", "Baterías"], datoCurioso: "Usado en monedas de muchos países." },
  { numero: 29, simbolo: "Cu", nombre: "Cobre", masa: 63.546, grupo: 11, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.90, radioAtomico: 145, configuracionElectronica: "[Ar] 3d¹⁰ 4s¹", usos: ["Cables eléctricos", "Tuberías", "Monedas"], datoCurioso: "Primer metal usado por humanos, excelente conductor." },
  { numero: 30, simbolo: "Zn", nombre: "Zinc", masa: 65.38, grupo: 12, periodo: 4, familia: "metales-transicion", estado: "solido", electronegatividad: 1.65, radioAtomico: 142, configuracionElectronica: "[Ar] 3d¹⁰ 4s²", usos: ["Galvanizado", "Baterías", "Suplementos"], datoCurioso: "Esencial para el sistema inmunológico." },
  { numero: 31, simbolo: "Ga", nombre: "Galio", masa: 69.723, grupo: 13, periodo: 4, familia: "otros-metales", estado: "solido", electronegatividad: 1.81, radioAtomico: 136, configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p¹", usos: ["Semiconductores", "LEDs", "Termómetros"], datoCurioso: "Se derrite en la mano (punto fusión 29.76°C)." },
  { numero: 32, simbolo: "Ge", nombre: "Germanio", masa: 72.63, grupo: 14, periodo: 4, familia: "metaloides", estado: "solido", electronegatividad: 2.01, radioAtomico: 125, configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p²", usos: ["Semiconductores", "Fibra óptica", "Detectores"], datoCurioso: "Predicho por Mendeleev como 'eka-silicio'." },
  { numero: 33, simbolo: "As", nombre: "Arsénico", masa: 74.922, grupo: 15, periodo: 4, familia: "metaloides", estado: "solido", electronegatividad: 2.18, radioAtomico: 114, configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p³", usos: ["Semiconductores", "Pesticidas", "Medicina"], datoCurioso: "Históricamente usado como veneno por su difícil detección." },
  { numero: 34, simbolo: "Se", nombre: "Selenio", masa: 78.96, grupo: 16, periodo: 4, familia: "no-metales", estado: "solido", electronegatividad: 2.55, radioAtomico: 103, configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p⁴", usos: ["Electrónica", "Vidrio", "Suplementos"], datoCurioso: "Esencial en pequeñas cantidades, tóxico en grandes." },
  { numero: 35, simbolo: "Br", nombre: "Bromo", masa: 79.904, grupo: 17, periodo: 4, familia: "halogenos", estado: "liquido", electronegatividad: 2.96, radioAtomico: 94, configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p⁵", usos: ["Retardantes de fuego", "Fotografía", "Medicina"], datoCurioso: "Único no metal líquido a temperatura ambiente." },
  { numero: 36, simbolo: "Kr", nombre: "Kriptón", masa: 83.798, grupo: 18, periodo: 4, familia: "gases-nobles", estado: "gas", electronegatividad: 3.00, radioAtomico: 88, configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p⁶", usos: ["Iluminación", "Láseres", "Fotografía"], datoCurioso: "Usado para definir el metro hasta 1983." },

  // Período 5
  { numero: 37, simbolo: "Rb", nombre: "Rubidio", masa: 85.468, grupo: 1, periodo: 5, familia: "metales-alcalinos", estado: "solido", electronegatividad: 0.82, radioAtomico: 265, configuracionElectronica: "[Kr] 5s¹", usos: ["Relojes atómicos", "Células fotoeléctricas"], datoCurioso: "Se enciende espontáneamente en el aire." },
  { numero: 38, simbolo: "Sr", nombre: "Estroncio", masa: 87.62, grupo: 2, periodo: 5, familia: "metales-alcalinoterreos", estado: "solido", electronegatividad: 0.95, radioAtomico: 219, configuracionElectronica: "[Kr] 5s²", usos: ["Fuegos artificiales rojos", "Imanes", "Vidrio"], datoCurioso: "Da color rojo brillante a los fuegos artificiales." },
  { numero: 39, simbolo: "Y", nombre: "Itrio", masa: 88.906, grupo: 3, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 1.22, radioAtomico: 212, configuracionElectronica: "[Kr] 4d¹ 5s²", usos: ["LEDs", "Superconductores", "Láseres"], datoCurioso: "Usado en pantallas de TV y monitores." },
  { numero: 40, simbolo: "Zr", nombre: "Circonio", masa: 91.224, grupo: 4, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 1.33, radioAtomico: 206, configuracionElectronica: "[Kr] 4d² 5s²", usos: ["Reactores nucleares", "Cerámica", "Joyería"], datoCurioso: "Muy resistente a la corrosión y al calor." },
  { numero: 41, simbolo: "Nb", nombre: "Niobio", masa: 92.906, grupo: 5, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 1.60, radioAtomico: 198, configuracionElectronica: "[Kr] 4d⁴ 5s¹", usos: ["Acero de alta resistencia", "Superconductores"], datoCurioso: "Brasil tiene las mayores reservas mundiales." },
  { numero: 42, simbolo: "Mo", nombre: "Molibdeno", masa: 95.95, grupo: 6, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 2.16, radioAtomico: 190, configuracionElectronica: "[Kr] 4d⁵ 5s¹", usos: ["Acero de alta temperatura", "Catalizadores"], datoCurioso: "Esencial para las enzimas de fijación de nitrógeno." },
  { numero: 43, simbolo: "Tc", nombre: "Tecnecio", masa: 98, grupo: 7, periodo: 5, familia: "metales-transicion", estado: "sintetico", electronegatividad: 1.90, radioAtomico: 183, configuracionElectronica: "[Kr] 4d⁵ 5s²", usos: ["Medicina nuclear", "Diagnóstico"], datoCurioso: "Primer elemento producido artificialmente." },
  { numero: 44, simbolo: "Ru", nombre: "Rutenio", masa: 101.07, grupo: 8, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 2.20, radioAtomico: 178, configuracionElectronica: "[Kr] 4d⁷ 5s¹", usos: ["Catalizadores", "Electrónica", "Joyería"], datoCurioso: "Uno de los metales más raros de la Tierra." },
  { numero: 45, simbolo: "Rh", nombre: "Rodio", masa: 102.91, grupo: 9, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 2.28, radioAtomico: 173, configuracionElectronica: "[Kr] 4d⁸ 5s¹", usos: ["Catalizadores de autos", "Joyería", "Espejos"], datoCurioso: "Uno de los elementos más caros del mundo." },
  { numero: 46, simbolo: "Pd", nombre: "Paladio", masa: 106.42, grupo: 10, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 2.20, radioAtomico: 169, configuracionElectronica: "[Kr] 4d¹⁰", usos: ["Catalizadores", "Electrónica", "Joyería"], datoCurioso: "Puede absorber 900 veces su volumen en hidrógeno." },
  { numero: 47, simbolo: "Ag", nombre: "Plata", masa: 107.87, grupo: 11, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 1.93, radioAtomico: 165, configuracionElectronica: "[Kr] 4d¹⁰ 5s¹", usos: ["Joyería", "Fotografía", "Electrónica"], datoCurioso: "Mejor conductor de electricidad y calor." },
  { numero: 48, simbolo: "Cd", nombre: "Cadmio", masa: 112.41, grupo: 12, periodo: 5, familia: "metales-transicion", estado: "solido", electronegatividad: 1.69, radioAtomico: 161, configuracionElectronica: "[Kr] 4d¹⁰ 5s²", usos: ["Baterías", "Pigmentos", "Recubrimientos"], datoCurioso: "Muy tóxico, causa la enfermedad de itai-itai." },
  { numero: 49, simbolo: "In", nombre: "Indio", masa: 114.82, grupo: 13, periodo: 5, familia: "otros-metales", estado: "solido", electronegatividad: 1.78, radioAtomico: 156, configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p¹", usos: ["Pantallas táctiles", "Soldaduras", "Semiconductores"], datoCurioso: "Emite un sonido característico al doblarse." },
  { numero: 50, simbolo: "Sn", nombre: "Estaño", masa: 118.71, grupo: 14, periodo: 5, familia: "otros-metales", estado: "solido", electronegatividad: 1.96, radioAtomico: 145, configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p²", usos: ["Soldaduras", "Latas", "Bronce"], datoCurioso: "Conocido desde la antigüedad (Edad de Bronce)." },
  { numero: 51, simbolo: "Sb", nombre: "Antimonio", masa: 121.76, grupo: 15, periodo: 5, familia: "metaloides", estado: "solido", electronegatividad: 2.05, radioAtomico: 133, configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p³", usos: ["Aleaciones", "Retardantes de fuego", "Baterías"], datoCurioso: "Usado en cosméticos desde el antiguo Egipto." },
  { numero: 52, simbolo: "Te", nombre: "Telurio", masa: 127.60, grupo: 16, periodo: 5, familia: "metaloides", estado: "solido", electronegatividad: 2.10, radioAtomico: 123, configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p⁴", usos: ["Semiconductores", "Aleaciones", "Energía solar"], datoCurioso: "Da mal aliento característico a quienes lo manejan." },
  { numero: 53, simbolo: "I", nombre: "Yodo", masa: 126.90, grupo: 17, periodo: 5, familia: "halogenos", estado: "solido", electronegatividad: 2.66, radioAtomico: 115, configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p⁵", usos: ["Medicina", "Fotografía", "Sal yodada"], datoCurioso: "Esencial para la función tiroidea." },
  { numero: 54, simbolo: "Xe", nombre: "Xenón", masa: 131.29, grupo: 18, periodo: 5, familia: "gases-nobles", estado: "gas", electronegatividad: 2.60, radioAtomico: 108, configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p⁶", usos: ["Iluminación", "Anestesia", "Propulsión espacial"], datoCurioso: "Primer gas noble en formar compuestos químicos." },

  // Período 6
  { numero: 55, simbolo: "Cs", nombre: "Cesio", masa: 132.91, grupo: 1, periodo: 6, familia: "metales-alcalinos", estado: "solido", electronegatividad: 0.79, radioAtomico: 298, configuracionElectronica: "[Xe] 6s¹", usos: ["Relojes atómicos", "Células fotoeléctricas"], datoCurioso: "Define el segundo en el Sistema Internacional." },
  { numero: 56, simbolo: "Ba", nombre: "Bario", masa: 137.33, grupo: 2, periodo: 6, familia: "metales-alcalinoterreos", estado: "solido", electronegatividad: 0.89, radioAtomico: 253, configuracionElectronica: "[Xe] 6s²", usos: ["Rayos X (contraste)", "Fuegos artificiales verdes"], datoCurioso: "Usado en medicina para radiografías del tracto digestivo." },

  // Lantánidos (57-71)
  { numero: 57, simbolo: "La", nombre: "Lantano", masa: 138.91, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.10, radioAtomico: 195, configuracionElectronica: "[Xe] 5d¹ 6s²", usos: ["Lentes de cámara", "Baterías híbridas"], datoCurioso: "Da nombre a los lantánidos o tierras raras." },
  { numero: 58, simbolo: "Ce", nombre: "Cerio", masa: 140.12, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.12, radioAtomico: 185, configuracionElectronica: "[Xe] 4f¹ 5d¹ 6s²", usos: ["Catalizadores", "Pulido de vidrio", "Encendedores"], datoCurioso: "Lantánido más abundante en la corteza terrestre." },
  { numero: 59, simbolo: "Pr", nombre: "Praseodimio", masa: 140.91, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.13, radioAtomico: 247, configuracionElectronica: "[Xe] 4f³ 6s²", usos: ["Imanes", "Vidrio verde", "Láseres"], datoCurioso: "Da color verde a los vidrios de soldador." },
  { numero: 60, simbolo: "Nd", nombre: "Neodimio", masa: 144.24, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.14, radioAtomico: 206, configuracionElectronica: "[Xe] 4f⁴ 6s²", usos: ["Imanes potentes", "Láseres", "Vidrio"], datoCurioso: "Los imanes más fuertes del mundo contienen neodimio." },
  { numero: 61, simbolo: "Pm", nombre: "Prometio", masa: 145, grupo: 3, periodo: 6, familia: "lantanidos", estado: "sintetico", electronegatividad: 1.13, radioAtomico: 205, configuracionElectronica: "[Xe] 4f⁵ 6s²", usos: ["Baterías nucleares", "Pintura luminosa"], datoCurioso: "Único lantánido radiactivo sin isótopos estables." },
  { numero: 62, simbolo: "Sm", nombre: "Samario", masa: 150.36, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.17, radioAtomico: 238, configuracionElectronica: "[Xe] 4f⁶ 6s²", usos: ["Imanes", "Reactores nucleares", "Medicina"], datoCurioso: "Usado en tratamiento del cáncer de próstata." },
  { numero: 63, simbolo: "Eu", nombre: "Europio", masa: 151.96, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.20, radioAtomico: 231, configuracionElectronica: "[Xe] 4f⁷ 6s²", usos: ["Pantallas de TV", "Billetes (seguridad)", "LEDs"], datoCurioso: "Da color rojo a las pantallas de TV antiguas." },
  { numero: 64, simbolo: "Gd", nombre: "Gadolinio", masa: 157.25, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.20, radioAtomico: 233, configuracionElectronica: "[Xe] 4f⁷ 5d¹ 6s²", usos: ["Resonancias magnéticas", "Reactores nucleares"], datoCurioso: "Usado como agente de contraste en MRI." },
  { numero: 65, simbolo: "Tb", nombre: "Terbio", masa: 158.93, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.20, radioAtomico: 225, configuracionElectronica: "[Xe] 4f⁹ 6s²", usos: ["Pantallas de TV", "Láseres", "Aleaciones"], datoCurioso: "Da color verde a las pantallas fluorescentes." },
  { numero: 66, simbolo: "Dy", nombre: "Disprosio", masa: 162.50, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.22, radioAtomico: 228, configuracionElectronica: "[Xe] 4f¹⁰ 6s²", usos: ["Imanes", "Reactores nucleares", "Láseres"], datoCurioso: "Tiene la mayor susceptibilidad magnética." },
  { numero: 67, simbolo: "Ho", nombre: "Holmio", masa: 164.93, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.23, radioAtomico: 226, configuracionElectronica: "[Xe] 4f¹¹ 6s²", usos: ["Imanes", "Láseres quirúrgicos", "Reactores"], datoCurioso: "Tiene el mayor momento magnético de cualquier elemento." },
  { numero: 68, simbolo: "Er", nombre: "Erbio", masa: 167.26, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.24, radioAtomico: 226, configuracionElectronica: "[Xe] 4f¹² 6s²", usos: ["Fibra óptica", "Láseres", "Metalurgia"], datoCurioso: "Amplifica señales en cables de fibra óptica." },
  { numero: 69, simbolo: "Tm", nombre: "Tulio", masa: 168.93, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.25, radioAtomico: 222, configuracionElectronica: "[Xe] 4f¹³ 6s²", usos: ["Rayos X portátiles", "Láseres"], datoCurioso: "Lantánido más raro después del prometio." },
  { numero: 70, simbolo: "Yb", nombre: "Iterbio", masa: 173.05, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.10, radioAtomico: 222, configuracionElectronica: "[Xe] 4f¹⁴ 6s²", usos: ["Metalurgia", "Láseres", "Medicina"], datoCurioso: "Puede mejorar las propiedades del acero inoxidable." },
  { numero: 71, simbolo: "Lu", nombre: "Lutecio", masa: 174.97, grupo: 3, periodo: 6, familia: "lantanidos", estado: "solido", electronegatividad: 1.27, radioAtomico: 217, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹ 6s²", usos: ["PET scans", "Catalizadores", "Datación geológica"], datoCurioso: "Último y más denso de los lantánidos." },

  // Continuación Período 6 (después de lantánidos)
  { numero: 72, simbolo: "Hf", nombre: "Hafnio", masa: 178.49, grupo: 4, periodo: 6, familia: "metales-transicion", estado: "solido", electronegatividad: 1.30, radioAtomico: 208, configuracionElectronica: "[Xe] 4f¹⁴ 5d² 6s²", usos: ["Reactores nucleares", "Procesadores", "Aleaciones"], datoCurioso: "Muy similar al circonio, difícil de separar." },
  { numero: 73, simbolo: "Ta", nombre: "Tantalio", masa: 180.95, grupo: 5, periodo: 6, familia: "metales-transicion", estado: "solido", electronegatividad: 1.50, radioAtomico: 200, configuracionElectronica: "[Xe] 4f¹⁴ 5d³ 6s²", usos: ["Electrónica", "Implantes quirúrgicos", "Capacitores"], datoCurioso: "Extremadamente resistente a la corrosión." },
  { numero: 74, simbolo: "W", nombre: "Tungsteno", masa: 183.84, grupo: 6, periodo: 6, familia: "metales-transicion", estado: "solido", electronegatividad: 2.36, radioAtomico: 193, configuracionElectronica: "[Xe] 4f¹⁴ 5d⁴ 6s²", usos: ["Filamentos de bombillas", "Herramientas de corte"], datoCurioso: "Tiene el punto de fusión más alto de todos los elementos." },
  { numero: 75, simbolo: "Re", nombre: "Renio", masa: 186.21, grupo: 7, periodo: 6, familia: "metales-transicion", estado: "solido", electronegatividad: 1.90, radioAtomico: 188, configuracionElectronica: "[Xe] 4f¹⁴ 5d⁵ 6s²", usos: ["Motores de avión", "Catalizadores", "Termopares"], datoCurioso: "Último elemento estable descubierto (1925)." },
  { numero: 76, simbolo: "Os", nombre: "Osmio", masa: 190.23, grupo: 8, periodo: 6, familia: "metales-transicion", estado: "solido", electronegatividad: 2.20, radioAtomico: 185, configuracionElectronica: "[Xe] 4f¹⁴ 5d⁶ 6s²", usos: ["Puntas de plumas", "Implantes", "Catalizadores"], datoCurioso: "Es el elemento más denso conocido." },
  { numero: 77, simbolo: "Ir", nombre: "Iridio", masa: 192.22, grupo: 9, periodo: 6, familia: "metales-transicion", estado: "solido", electronegatividad: 2.20, radioAtomico: 180, configuracionElectronica: "[Xe] 4f¹⁴ 5d⁷ 6s²", usos: ["Bujías", "Crisoles", "Electrodos"], datoCurioso: "Segundo elemento más denso, muy resistente a corrosión." },
  { numero: 78, simbolo: "Pt", nombre: "Platino", masa: 195.08, grupo: 10, periodo: 6, familia: "metales-transicion", estado: "solido", electronegatividad: 2.28, radioAtomico: 177, configuracionElectronica: "[Xe] 4f¹⁴ 5d⁹ 6s¹", usos: ["Joyería", "Catalizadores de autos", "Medicina"], datoCurioso: "Usado en quimioterapia contra el cáncer." },
  { numero: 79, simbolo: "Au", nombre: "Oro", masa: 196.97, grupo: 11, periodo: 6, familia: "metales-transicion", estado: "solido", electronegatividad: 2.54, radioAtomico: 174, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹", usos: ["Joyería", "Electrónica", "Reserva monetaria"], datoCurioso: "Todo el oro extraído cabría en un cubo de 21 metros." },
  { numero: 80, simbolo: "Hg", nombre: "Mercurio", masa: 200.59, grupo: 12, periodo: 6, familia: "metales-transicion", estado: "liquido", electronegatividad: 2.00, radioAtomico: 171, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s²", usos: ["Termómetros", "Amalgamas dentales", "Lámparas"], datoCurioso: "Único metal líquido a temperatura ambiente." },
  { numero: 81, simbolo: "Tl", nombre: "Talio", masa: 204.38, grupo: 13, periodo: 6, familia: "otros-metales", estado: "solido", electronegatividad: 1.62, radioAtomico: 156, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", usos: ["Electrónica", "Medicina nuclear"], datoCurioso: "Extremadamente tóxico, usado en venenos para ratas." },
  { numero: 82, simbolo: "Pb", nombre: "Plomo", masa: 207.2, grupo: 14, periodo: 6, familia: "otros-metales", estado: "solido", electronegatividad: 2.33, radioAtomico: 154, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", usos: ["Baterías", "Protección radiológica", "Soldaduras"], datoCurioso: "Conocido desde la antigüedad, muy tóxico." },
  { numero: 83, simbolo: "Bi", nombre: "Bismuto", masa: 208.98, grupo: 15, periodo: 6, familia: "otros-metales", estado: "solido", electronegatividad: 2.02, radioAtomico: 143, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", usos: ["Medicina (Pepto-Bismol)", "Aleaciones", "Cosméticos"], datoCurioso: "Elemento más pesado con isótopo estable." },
  { numero: 84, simbolo: "Po", nombre: "Polonio", masa: 209, grupo: 16, periodo: 6, familia: "metaloides", estado: "solido", electronegatividad: 2.00, radioAtomico: 135, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", usos: ["Eliminadores de estática", "Fuentes de calor"], datoCurioso: "Descubierto por Marie Curie, nombrado por Polonia." },
  { numero: 85, simbolo: "At", nombre: "Astato", masa: 210, grupo: 17, periodo: 6, familia: "halogenos", estado: "sintetico", electronegatividad: 2.20, radioAtomico: 127, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", usos: ["Medicina nuclear (investigación)"], datoCurioso: "Elemento más raro de la Tierra, solo ~25g en corteza." },
  { numero: 86, simbolo: "Rn", nombre: "Radón", masa: 222, grupo: 18, periodo: 6, familia: "gases-nobles", estado: "gas", electronegatividad: 2.20, radioAtomico: 120, configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", usos: ["Tratamiento del cáncer (histórico)"], datoCurioso: "Gas radiactivo, segunda causa de cáncer de pulmón." },

  // Período 7
  { numero: 87, simbolo: "Fr", nombre: "Francio", masa: 223, grupo: 1, periodo: 7, familia: "metales-alcalinos", estado: "sintetico", electronegatividad: 0.70, radioAtomico: 348, configuracionElectronica: "[Rn] 7s¹", usos: ["Investigación científica"], datoCurioso: "Metal alcalino más reactivo, muy raro y radiactivo." },
  { numero: 88, simbolo: "Ra", nombre: "Radio", masa: 226, grupo: 2, periodo: 7, familia: "metales-alcalinoterreos", estado: "solido", electronegatividad: 0.90, radioAtomico: 283, configuracionElectronica: "[Rn] 7s²", usos: ["Tratamiento del cáncer (histórico)", "Pintura luminosa"], datoCurioso: "Descubierto por Marie y Pierre Curie." },

  // Actínidos (89-103)
  { numero: 89, simbolo: "Ac", nombre: "Actinio", masa: 227, grupo: 3, periodo: 7, familia: "actinidos", estado: "solido", electronegatividad: 1.10, radioAtomico: 260, configuracionElectronica: "[Rn] 6d¹ 7s²", usos: ["Fuente de neutrones", "Medicina nuclear"], datoCurioso: "Da nombre a la serie de los actínidos." },
  { numero: 90, simbolo: "Th", nombre: "Torio", masa: 232.04, grupo: 3, periodo: 7, familia: "actinidos", estado: "solido", electronegatividad: 1.30, radioAtomico: 237, configuracionElectronica: "[Rn] 6d² 7s²", usos: ["Reactores nucleares", "Lámparas de gas"], datoCurioso: "Puede ser combustible nuclear alternativo al uranio." },
  { numero: 91, simbolo: "Pa", nombre: "Protactinio", masa: 231.04, grupo: 3, periodo: 7, familia: "actinidos", estado: "solido", electronegatividad: 1.50, radioAtomico: 243, configuracionElectronica: "[Rn] 5f² 6d¹ 7s²", usos: ["Investigación científica"], datoCurioso: "Uno de los elementos naturales más raros." },
  { numero: 92, simbolo: "U", nombre: "Uranio", masa: 238.03, grupo: 3, periodo: 7, familia: "actinidos", estado: "solido", electronegatividad: 1.38, radioAtomico: 240, configuracionElectronica: "[Rn] 5f³ 6d¹ 7s²", usos: ["Energía nuclear", "Armas nucleares", "Blindaje"], datoCurioso: "Más denso que el plomo, ligeramente radiactivo." },
  { numero: 93, simbolo: "Np", nombre: "Neptunio", masa: 237, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.36, radioAtomico: 221, configuracionElectronica: "[Rn] 5f⁴ 6d¹ 7s²", usos: ["Detectores de neutrones", "Investigación"], datoCurioso: "Primer elemento transurámico descubierto." },
  { numero: 94, simbolo: "Pu", nombre: "Plutonio", masa: 244, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.28, radioAtomico: 243, configuracionElectronica: "[Rn] 5f⁶ 7s²", usos: ["Armas nucleares", "Sondas espaciales", "Reactores"], datoCurioso: "Usado en la bomba de Nagasaki." },
  { numero: 95, simbolo: "Am", nombre: "Americio", masa: 243, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: 244, configuracionElectronica: "[Rn] 5f⁷ 7s²", usos: ["Detectores de humo", "Medidores industriales"], datoCurioso: "Presente en detectores de humo domésticos." },
  { numero: 96, simbolo: "Cm", nombre: "Curio", masa: 247, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: 245, configuracionElectronica: "[Rn] 5f⁷ 6d¹ 7s²", usos: ["Sondas espaciales", "Fuente de calor"], datoCurioso: "Nombrado en honor a Marie y Pierre Curie." },
  { numero: 97, simbolo: "Bk", nombre: "Berkelio", masa: 247, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: 244, configuracionElectronica: "[Rn] 5f⁹ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Berkeley, California." },
  { numero: 98, simbolo: "Cf", nombre: "Californio", masa: 251, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: 245, configuracionElectronica: "[Rn] 5f¹⁰ 7s²", usos: ["Detectores de metales", "Análisis de materiales"], datoCurioso: "Uno de los elementos más caros (~$27M/gramo)." },
  { numero: 99, simbolo: "Es", nombre: "Einstenio", masa: 252, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: 245, configuracionElectronica: "[Rn] 5f¹¹ 7s²", usos: ["Investigación científica"], datoCurioso: "Descubierto en residuos de la primera bomba H." },
  { numero: 100, simbolo: "Fm", nombre: "Fermio", masa: 257, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹² 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado en honor a Enrico Fermi." },
  { numero: 101, simbolo: "Md", nombre: "Mendelevio", masa: 258, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹³ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado en honor a Dmitri Mendeléiev." },
  { numero: 102, simbolo: "No", nombre: "Nobelio", masa: 259, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado en honor a Alfred Nobel." },
  { numero: 103, simbolo: "Lr", nombre: "Lawrencio", masa: 262, grupo: 3, periodo: 7, familia: "actinidos", estado: "sintetico", electronegatividad: 1.30, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 7s² 7p¹", usos: ["Investigación científica"], datoCurioso: "Último actínido, nombrado por Ernest Lawrence." },

  // Elementos transactínidos (104-118)
  { numero: 104, simbolo: "Rf", nombre: "Rutherfordio", masa: 267, grupo: 4, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d² 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Ernest Rutherford." },
  { numero: 105, simbolo: "Db", nombre: "Dubnio", masa: 268, grupo: 5, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d³ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Dubna, Rusia." },
  { numero: 106, simbolo: "Sg", nombre: "Seaborgio", masa: 271, grupo: 6, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d⁴ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Glenn T. Seaborg en vida." },
  { numero: 107, simbolo: "Bh", nombre: "Bohrio", masa: 272, grupo: 7, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d⁵ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Niels Bohr." },
  { numero: 108, simbolo: "Hs", nombre: "Hasio", masa: 270, grupo: 8, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d⁶ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Hesse, Alemania." },
  { numero: 109, simbolo: "Mt", nombre: "Meitnerio", masa: 276, grupo: 9, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d⁷ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Lise Meitner." },
  { numero: 110, simbolo: "Ds", nombre: "Darmstadtio", masa: 281, grupo: 10, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d⁸ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Darmstadt, Alemania." },
  { numero: 111, simbolo: "Rg", nombre: "Roentgenio", masa: 280, grupo: 11, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d⁹ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Wilhelm Röntgen." },
  { numero: 112, simbolo: "Cn", nombre: "Copernicio", masa: 285, grupo: 12, periodo: 7, familia: "metales-transicion", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Nicolás Copérnico." },
  { numero: 113, simbolo: "Nh", nombre: "Nihonio", masa: 284, grupo: 13, periodo: 7, familia: "otros-metales", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", usos: ["Investigación científica"], datoCurioso: "Primer elemento descubierto en Asia (Japón)." },
  { numero: 114, simbolo: "Fl", nombre: "Flerovio", masa: 289, grupo: 14, periodo: 7, familia: "otros-metales", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", usos: ["Investigación científica"], datoCurioso: "Nombrado por Georgy Flyorov." },
  { numero: 115, simbolo: "Mc", nombre: "Moscovio", masa: 288, grupo: 15, periodo: 7, familia: "otros-metales", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", usos: ["Investigación científica"], datoCurioso: "Nombrado por la región de Moscú." },
  { numero: 116, simbolo: "Lv", nombre: "Livermorio", masa: 293, grupo: 16, periodo: 7, familia: "otros-metales", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", usos: ["Investigación científica"], datoCurioso: "Nombrado por el Laboratorio Lawrence Livermore." },
  { numero: 117, simbolo: "Ts", nombre: "Teneso", masa: 294, grupo: 17, periodo: 7, familia: "halogenos", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", usos: ["Investigación científica"], datoCurioso: "Nombrado por Tennessee, EE.UU." },
  { numero: 118, simbolo: "Og", nombre: "Oganesón", masa: 294, grupo: 18, periodo: 7, familia: "gases-nobles", estado: "sintetico", electronegatividad: null, radioAtomico: null, configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", usos: ["Investigación científica"], datoCurioso: "Elemento más pesado conocido, nombrado por Yuri Oganessian." },
];

// Mapa rápido símbolo -> elemento para calculadora de masa molar
export const elementosPorSimbolo: Record<string, Elemento> = {};
elementos.forEach(el => {
  elementosPorSimbolo[el.simbolo] = el;
});
